functionsDirectory = "/Users/joestrazza/sprintai-ordering/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/joestrazza/sprintai-ordering/public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && bash scripts/build-public-site.sh"
functions = "/Users/joestrazza/sprintai-ordering/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/admin/assets/*"
to = "/assets/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/icons/*"
to = "/icons/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/manifest.json"
to = "/manifest.json"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/webhook"
to = "/.netlify/functions/stripe-webhook"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/create-checkout-session"
to = "/.netlify/functions/create-checkout-session"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sms-webhook"
to = "/.netlify/functions/sms-webhook"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin"
to = "https://sprintai-chat-admin.netlify.app/admin"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "https://sprintai-chat-admin.netlify.app/admin/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/chat/*"
to = "/chat/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]